name: Archive
on:
  workflow_dispatch:
    inputs:
      url:
        description: URL
        required: true
      cookies:
        description: Cookies

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Download
        run: printf "%s\n" "FILENAME=$(curl -fsSLOJ -w %{filename_effective} -b "${{ inputs.cookies }}" "${{ inputs.url }}")" >> "$GITHUB_ENV"

      - name: Download and run
        run: |
          cksum -a sha256 "$FILENAME"
          7z a -m0=lzma2 -mx=9 "$FILENAME.7z "$filename"

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ${{ env.FILENAME }}.7z
