name: Checksum
on:
  workflow_dispatch:
    inputs:
      cookies:
        description: Cookies
      file-url:
        description: File URL
        required: true

jobs:
  checksum:
    runs-on: ubuntu-latest
    steps:
      - name: Checksum
        run: |
          filename="$(curl -sSLOJ -w "%{filename_effective}" -b "${{ inputs.cookies }}" "${{ inputs.file-url }}")"

          if [[ "$filename" == *.zip ]]; then
            unzip -q "$filename"
          fi

          find . -type f -exec cksum -a sha256 {} +
