name: Compress Videos
run-name: Compress Videos (${{ inputs.max-resolution }}p, ${{ inputs.include-audio && 'Audio' || 'No Audio' }})
on:
  workflow_dispatch:
    inputs:
      urls:
        description: URLs
        default: "['URL_HERE']"
        required: true
      cookies:
        description: Cookies
      max-resolution:
        description: Max resolution
        default: "144"
        options: [1080, 720, 480, 360, 240, 144]
        type: choice
      include-audio:
        description: Include audio
        type: boolean

jobs:
  compress-videos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url: ${{ fromJson(inputs.urls) }}
    steps:
      - name: Download FFmpeg and video
        run: |
          curl -sSL https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz | tar -xJ -f -

          filename="$(curl -sSLOJ -w %{filename_effective} -b "${{ inputs.cookies }}" "${{ matrix.url }}")"
          printf "%s\n" "INPUT_FILENAME=$filename" "OUTPUT_FILENAME=${filename%.*}.mkv" >> "$GITHUB_ENV"

      - name: Compress
        run: |
          ./*/bin/ffmpeg \
            -i "$INPUT_FILENAME" \
            -c:v libx265 \
            -crf 30 \
            -pix_fmt yuv420p10le \
            -vf "scale='if(gt(iw, ih), -2, min(iw, ${{ inputs.max-resolution }}))':'if(gt(iw, ih), min(ih, ${{ inputs.max-resolution }}), -2)'" \
            ${{ inputs.include-audio && '-c:a libopus' || '-an' }} \
            "$OUTPUT_FILENAME"

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ${{ env.OUTPUT_FILENAME }}

  merge:
    needs: compress-videos
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - run: 7z a -m0=lzma2 -mx=9 !videos.7z .

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: \!videos.7z
