name: File
on:
  workflow_dispatch:
    inputs:
      cookies:
        description: Cookies
      file-url:
        description: File URL
        required: true

jobs:
  file:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: printf "%s\n" "FILENAME=$(curl -sSLOJ -w "%{filename_effective}" -b "${{ inputs.cookies }}" "${{ inputs.file-url }}")" >> "$GITHUB_ENV"

      - name: File
        run: |
          7z x "$FILENAME" || true
          find . -type f -exec cksum -a sha256 {} +
          zip -q -d "$FILENAME" "lib/armeabi-v7a/*" "lib/x86/*" "lib/x86_64/*" && zip -q -d "$FILENAME" "META-INF/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ${{ env.FILENAME }}
