name: File
on:
  workflow_dispatch:
    inputs:
      cookies:
        description: Cookies
      file-url:
        description: File URL
        default: https://github.com/MojoLauncher/MojoLauncher/releases/download/nightly/MojoLauncher-release.apk
        required: true

jobs:
  file:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: printf "%s\n" "FILE=$(curl -sSLOJ -w "%{filename_effective}" -b "${{ inputs.cookies }}" "${{ inputs.file-url }}")" >> "$GITHUB_ENV"

      - name: File
        run: |
          if [[ "$FILE" == *.zip ]]; then
            unzip -q "$FILE"
            find . -type f -exec cksum -a sha256 {} +
          elif [[ "$FILE" == *.apk ]]; then
            zip -q -d "$FILE" "lib/armeabi-v7a/*" "lib/x86/*" "lib/x86_64/*" && zip -d "$FILE" "META-INF/*"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ${{ env.FILE }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: output
          path: ${{ env.FILE }}
