name: Generate Keystore
on: workflow_dispatch

jobs:
  generate-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin

      - name: Generate keystore
        run: |
          keystore_password="$(head -c 16 /dev/urandom | base64)"
          keytool \
            -genkeypair \
            -keystore keystore.p12 \
            -storepass "$keystore_password" \
            -alias android \
            -keypass "$keystore_password" \
            -keyalg RSA \
            -dname "CN=Android" \
            -validity 10000

          printf "%s\n" "$keystore_password"

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: keystore.p12
