name: Generate Keystore
on:
  workflow_dispatch:
    inputs:
      alias:
        description: Alias
        required: true
      common-name:
        description: Common Name
        required: true
      password:
        description: Password
        required: true

jobs:
  generate-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          java-version: latest
          distribution: temurin

      - name: Generate keystore
        env:
          ALIAS: ${{ inputs.alias }}
          COMMON_NAME: ${{ inputs.common-name }}
          PASSWORD: ${{ inputs.password }}
        run: |
          keytool -genkeypair -alias "$ALIAS" -keyalg RSA -validity 10000 -dname "CN=$COMMON_NAME" -storepass "$PASSWORD"
          base64 -w 0 ~/.keystore > base64.txt

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: base64.txt
