name: Test File
on:
  workflow_dispatch:
    inputs:
      cookies:
        description: Cookies
      file-url:
        description: File URL
        required: true

jobs:
  test-file:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: printf "%s\n" "FILENAME=$(curl -sSLOJ -w "%{filename_effective}" -b "${{ inputs.cookies }}" "${{ inputs.file-url }}")" >> "$GITHUB_ENV"

      - name: Test file
        run: |
          unzip -q "$FILENAME" || true
          find . -type f -exec cksum -a sha256 {} +

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ${{ env.FILENAME }}
